name: env-name-here-does-not-matter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - pip
  - pip:
    - KEGGDecoder
  - prokka
  - htseq
  - bowtie2
  - prodigal
  - kofamscan
